name: CI

on:

  schedule:
    - cron: "30 15 * * 1-5"
    - cron: "15 5 * * 6,0"

  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from repo
        uses: actions/checkout@v6

      - name: Install node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install newman + htmlextra reporter
        run: npm i -g newman newman-reporter-htmlextra
