name: CI

on:
  schedule:
    - cron: "30 15 * * 1-5"
    - cron: "15 5 * * 6,0"

  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code from repo
        uses: actions/checkout@v6

      - name: Install node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24

      - name: Install newman + htmlextra reporter
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Create reports directory
        run: mkdir -p reports

      - name: Run Newman Tests with CLI and HTML Reports
        run: |
          newman run Trello_Api_Dmitry.postman_collection.json \
          -e TrelloApiEnvironment.postman_environment.json \
          -r cli,htmlextra \
          --reporter-htmlextra-export ./reports/Trello_Api_Dmitry.postman_collection.html

      - name: Upload HTML Report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: Trello_Api_Dmitry.postman_collection-test-report
          path: reports/Trello_Api_Dmitry.postman_collection.html
